models/Product.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\ServerErrorHttpException;

/**
 * This is the model class for table "{{%product}}".
 *
 * @property integer $id
 * @property string $name
 * @property integer $category_id
 *
 * @property Modification[] $modifications
 * @property TradeOffer[] $tradeOffers
 * @property Category $category
 */
class Product extends ActiveRecord implements ActionButtonInterface
{
    /**
     * Имя класса, настоящего хозяина запрашиваемых данных
     * Костыль для вывода категорий рядом с продуктами в списке
     *
     * @var string
     */
    public $className;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%product}}';
    }

    public function scenarios()
    {
        return ArrayHelper::merge(parent::scenarios(), [
            self::SCENARIO_MIGRATION => ['name'],
        ]);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'category_id'], 'required'],
            [['name'], 'string', 'max' => 255],
            [['category_id'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
            'category_id' => 'Категория',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModifications()
    {
        return $this->hasMany(Modification::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTradeOffers()
    {
        return $this->hasMany(TradeOffer::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @inheritdoc
     */
    public function getButtonName()
    {
        return $this->name;
    }

    /**
     * Возвращает URL добавления продукта в позицию
     * @return string
     * @throws ServerErrorHttpException
     */
    public function getActionUrl()
    {
        if ($this->className && $this->className != self::className()) {
            $class = new $this->className;
            if (!method_exists($class, 'getActionUrl')) {
                throw new ServerErrorHttpException('Некорректный альтернативный класс');
            }
            $class->id = $this->id;
            $class->name = $this->name;
            return call_user_func([$class, 'getActionUrl']);
        }
        return Url::to(['/manager/add-product', 'product_id' => $this->id]);
    }

    const SCENARIO_MIGRATION = 'migration';
}

controllers/ManagerController.php
<?php

namespace app\controllers;

use app\libs\data\SessionDataProvider;
use app\libs\enums\OrderEvent;
use app\models\Category;
use app\models\Modification;
use app\models\Order;
use app\models\Position;
use app\models\Product;
use app\models\TradeOffer;
use izumi\longpoll\Event;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

class ManagerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->view->params['section_name'] = 'Панель менеджера';
        $this->view->params['home_url'] = ['/manager'];
        $this->view->params['header_menu'] = [
            ['label' => 'Панель сборщика', 'url' => ['/collector']],
        ];
    }

    /**
     * Список продуктов и заказов
     *
     * @param bool $category_id
     * @return string
     */
    public function actionIndex($category_id = false)
    {
        $this->view->params['fullHeight'] = true;
        /** @var Category $category */
        if ($category_id === false) {
            $category = Category::find()->where(['parent_id' => null])->orderBy(['ID' => SORT_ASC])->limit(1)->one();
        } else {
            $category = Category::findOne($category_id);
            if ($category === null) {
                return $this->redirectWithError(['/manager'], 'Некорректный запрос');
            }
        }
        $menuDataProvider = new ActiveDataProvider(['query' => $category->getChildren()]);
        $newOrderDataProvider = new SessionDataProvider(['sessionKey' => 'positions']);
        $ordersDataProvider = new ActiveDataProvider([
            'query' => Order::find()->where(['status' => Order::STATUS_COMPLETED]),
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_ASC,
                ],
            ],
        ]);
        return $this->render('index', [
            'menuDataProvider' => $menuDataProvider,
            'newOrderDataProvider' => $newOrderDataProvider,
            'ordersDataProvider' => $ordersDataProvider,
        ]);
    }

    /**
     * Дообавляет продукт и при необходимости создаёт позицию
     *
     * @param integer|bool $product_id
     * @return \yii\web\Response
     */
    public function actionAddProduct($product_id = false)
    {
        $product = Product::findOne($product_id);
        if ($product === null) {
            return $this->redirectWithError(['/manager'], 'Произошла ошибка');
        }
        Yii::$app->session['new_position'] = new Position(['product_id' => $product->id]);
        return $this->redirect(['/manager/select-offer']);
    }

    /**
     * Устанавливает торговое предложение
     *
     * @param integer|bool $trade_offer_id
     * @return string|\yii\web\Response
     */
    public function actionSelectOffer($trade_offer_id = false)
    {
        if ($trade_offer_id !== false) {
            $tradeOffer = TradeOffer::findOne($trade_offer_id);
            if ($tradeOffer === null) {
                return $this->redirectWithError(['/manager'], 'Произошла ошибка');
            } else {
                Yii::$app->session['new_position']->trade_offer_id = $tradeOffer->id;
                return $this->redirect(['/manager/select-modification']);
            }
        }
        $tradeOffers = Yii::$app->session['new_position']->product->tradeOffers;
        if (count($tradeOffers) > 1 || count($tradeOffers) == 1 && $tradeOffers[0]->name != '-') {
            /** @var Position $position */
            $position = Yii::$app->session['new_position'];
            $dataProvider = new ActiveDataProvider(['query' => $position->product->getTradeOffers()]);
            return $this->render('select-trade-offer', [
                'dataProvider' => $dataProvider,
            ]);
        } elseif (count($tradeOffers) == 1) {
            Yii::$app->session['new_position']->trade_offer_id = $tradeOffers[0]->id;
            return $this->redirect(['/manager/select-modification']);
        } else {
            return $this->redirectWithError(['/manager'], 'Для продукта не созданы торговые предложения');
        }
    }

    /**
     * Устанавливает модификацию
     *
     * @param integer|bool $modification_id
     * @return string|\yii\web\Response
     */
    public function actionSelectModification($modification_id = false)
    {
        if ($modification_id !== false) {
            $modification = Modification::findOne($modification_id);
            if ($modification === null) {
                return $this->redirectWithError(['/manager'], 'Произошла ошибка');
            } else {
                Yii::$app->session['new_position']->modification_id = $modification->id;
                return $this->redirect(['/manager/set-count']);
            }
        }
        $modifications = Yii::$app->session['new_position']->product->modifications;
        if (empty($modifications)) {
            return $this->redirect(['/manager/set-count']);
        } else {
            /** @var Position $position */
            $position = Yii::$app->session['new_position'];
            $dataProvider = new ActiveDataProvider(['query' => $position->product->getModifications()]);
            return $this->render('select-modification', [
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    /**
     * Устанавливает количество для позиции
     *
     * @param integer|bool $count
     * @return string|\yii\web\Response
     */
    public function actionSetCount($count = false)
    {
        if ($count !== false) {
            Yii::$app->session['new_position']->count = $count;
            if (!isset(Yii::$app->session['positions'])) {
                Yii::$app->session['positions'] = [];
            }
            Yii::$app->session['positions'] = array_merge(Yii::$app->session['positions'], [Yii::$app->session['new_position']]);
            unset(Yii::$app->session['new_position']);
            return $this->redirect(['/manager']);
        }
        return $this->render('set-count');
    }

    /**
     * Создаёт заказ из выбранных позиций
     *
     * @return \yii\web\Response
     */
    public function actionCreateOrder()
    {
        /** @var Position[] $positions */
        if (!($positions = Yii::$app->session['positions'])) {
            return $this->redirectWithError(['/manager'], 'Не выбраны позиции');
        }
        $order = new Order([
            'cost' => array_sum(array_map(
                function ($price, $count) {
                    return $price * $count;
                },
                ArrayHelper::getColumn($positions, 'tradeOffer.price'),
                ArrayHelper::getColumn($positions, 'count')
            )),
            'status' => Order::STATUS_COMPLETED,
            'created_at' => time(),
        ]);
        $transaction = Yii::$app->db->beginTransaction();
        if (!$order->save()) {
            $transaction->rollBack();
            return $this->redirectWithError(['/manager'], 'Произошла ошибка при создании заказа');
        }
        $success = true;
        array_map(function (Position $position) use ($order, &$success) {
            $position->order_id = $order->id;
            $success = $success && $position->save();
        }, $positions);
        if (!$success) {
            $transaction->rollBack();
            return $this->redirectWithError(['/manager'], 'Произошла ошибка при сохранении позиций');
        }
        $transaction->commit();
        Order::clearNewOrderData();
        Event::triggerByKey(OrderEvent::ORDER_CREATED);
        return $this->redirectWithSuccess(['/manager'], "Заказ № {$order->id} успешно создан!");
    }

    /**
     * Отменяет создание нового заказа
     *
     * @return \yii\web\Response
     */
    public function actionCancelOrder()
    {
        Order::clearNewOrderData();
        return $this->redirectWithSuccess(['/manager'], 'Создание заказа отменено');
    }

    /**
     * Завершает работу над заказом
     *
     * @param integer $id Идентификатор заказа
     * @return \yii\web\Response
     */
    public function actionCompleteOrder($id)
    {
        /** @var Order $order */
        $order = Order::findOne(['id' => $id, 'status' => Order::STATUS_COMPLETED]);
        if ($order === null) {
            return $this->redirectWithError(['/manager'], 'Заказ не найден');
        }
        $order->status = Order::STATUS_DELETED;
        $order->completed_at = time();
        $order->save();
        Event::triggerByKey(OrderEvent::ORDER_DELETED);
        return $this->redirectWithSuccess(['/manager'], 'Заказ №' . $order->id . ' завершён!');
    }

    /**
     * Удаляет позицию из создаваемого заказа
     *
     * @param integer $key
     * @return \yii\web\Response
     */
    public function actionDeletePosition($key)
    {
        $positions = Yii::$app->session['positions'];
        if (!isset($positions[$key])) {
            return $this->redirectWithError(['/manager', 'Позиция не существует']);
        }
        unset($positions[$key]);
        Yii::$app->session['positions'] = array_values($positions);
        return $this->redirect(['/manager']);
    }

    /**
     * Возвращает редирект с установкой сообщения об ошибке
     *
     * @param array|string $url
     * @param string|bool $message
     * @param int $statusCode
     * @return \yii\web\Response
     */
    private function redirectWithError($url, $message = true, $statusCode = 302)
    {
        Yii::$app->session->setFlash('error', $message);
        return $this->redirect($url, $statusCode);
    }

    /**
     * Возвращает редирект с установкой сообщения об успешно выполненных действиях
     *
     * @param array|string $url
     * @param string|bool $message
     * @param int $statusCode
     * @return \yii\web\Response
     */
    private function redirectWithSuccess($url, $message = true, $statusCode = 302)
    {
        Yii::$app->session->setFlash('success', $message);

views/manager/_order-item.php
<?php
/**
 * @var \yii\web\View $this
 * @var \app\models\Order $model
 */

use rmrevin\yii\fontawesome\FA;
use yii\bootstrap\Html;

?>
<div class="panel panel-primary b-order">
    <div class="panel-heading b-order__header">
        <strong class="b-order__label">Заказ №<?= $model->number ?></strong>
        <span class="b-order__time">(<?= $model->getCreateTime('H:i') ?>)</span>
        <?= Html::a(FA::icon('check'), ['/manager/complete-order', 'id' => $model->id], [
            'class' => 'text-white pull-right b-complete-mark b-order__complete-mark',
        ]) ?>
    </div>
    <ul class="list-group b-positions-list">
        <?php foreach ($model->positions as $position): ?>
            <li class="list-group-item list-group-item-info b-positions-list__position b-positions-list__position_info"><?= $position->positionData ?></li>
        <?php endforeach ?>
    </ul>
    <div class="panel-body">
        Итого: <?= Yii::$app->formatter->asCurrency($model->cost) ?>
    </div>
</div>

views/manager/_touch-button.php
<?php
/**
 * @var \app\models\ActionButtonInterface $model
 */

use yii\bootstrap\Html;
?>
<?= Html::a($model->buttonName, $model->actionUrl, ['class' => 'b-touch-button b-touch-buttons__btn']) ?>

views/manager/index.php
<?php
/**
 * @var $this yii\web\View
 * @var \yii\data\ActiveDataProvider $menuDataProvider
 * @var \app\libs\data\SessionDataProvider $newOrderDataProvider
 * @var \yii\data\ActiveDataProvider $ordersDataProvider
 */

use app\libs\widgets\NewOrder;
use yii\bootstrap\Alert;
use yii\bootstrap\Html;
use yii\widgets\ListView;

$this->title = 'Панель менеджера';
?>
<div class="b-manager-panel full-height">
    <div class="row full-height">
        <div class="col-md-8 full-height overflow-auto">
            <h1><?= Html::encode($this->title) ?></h1>
            <?php if (($error = Yii::$app->session->getFlash('error')) !== null): ?>
                <?= Alert::widget([
                    'options' => [
                        'class' => 'alert-danger',
                    ],
                    'body' => $error,
                ]) ?>
            <?php endif ?>
            <?php if (($success = Yii::$app->session->getFlash('success')) !== null): ?>
                <?= Alert::widget([
                    'options' => [
                        'class' => 'alert-success',
                    ],
                    'body' => $success,
                ]) ?>
            <?php endif ?>
            <?php if ($newOrderDataProvider->count > 0): ?>
                <?= NewOrder::widget(['dataProvider' => $newOrderDataProvider]) ?>
            <?php endif ?>
            <?= ListView::widget([
                'dataProvider' => $menuDataProvider,
                'itemView' => '_touch-button',
                'summary' => false,
                'options' => [
                    'class' => 'b-touch-buttons row',
                ],
                'itemOptions' => [
                    'class' => 'b-touch-buttons__btn-wrap col-lg-3 col-sm-4 col-xs-6',
                ],
            ]) ?>
        </div>
        <div class="b-orders-column col-md-4 full-height overflow-auto">
            <?= ListView::widget([
                'dataProvider' => $ordersDataProvider,
                'itemView' => '_order-item',
                'emptyText' => 'Нет актуальных заказов.',
                'summary' => false,
            ]) ?>
        </div>
    </div>
</div>

views/manager/select-modification.php
<?php
/**
 * @var $this yii\web\View
 * @var \yii\data\ActiveDataProvider $dataProvider
 */

use yii\bootstrap\Html;
use yii\widgets\ListView;

$this->title = 'Выбор модификации';
?>
<div class="b-select-trade-offer">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-md-12">
            <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_touch-button',
                'summary' => false,
                'options' => [
                    'class' => 'b-touch-buttons row',
                ],
                'itemOptions' => [
                    'class' => 'b-touch-buttons__btn-wrap col-lg-3 col-sm-4 col-xs-6',
                ],
            ]) ?>
        </div>
    </div>
</div>

views/manager/select-trade-offer.php
<?php
/**
 * @var $this yii\web\View
 * @var \yii\data\ActiveDataProvider $dataProvider
 */

use yii\bootstrap\Html;
use yii\widgets\ListView;

$this->title = 'Выбор предложения';
?>
<div class="b-select-trade-offer">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-md-12">
            <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_touch-button',
                'summary' => false,
                'options' => [
                    'class' => 'b-touch-buttons row',
                ],
                'itemOptions' => [
                    'class' => 'b-touch-buttons__btn-wrap col-lg-3 col-sm-4 col-xs-6',
                ],
            ]) ?>
        </div>
    </div>
</div>

views/manager/set-count.php
<?php
/**
 * @var $this yii\web\View
 */

use app\assets\CountAsset;
use rmrevin\yii\fontawesome\FA;
use yii\bootstrap\Html;

$this->title = 'Количество';

CountAsset::register($this);
?>
<div class="b-select-trade-offer">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= Html::beginForm('', 'get') ?>
    <div class="b-count-input js-count-input row">
        <div class="b-count-input__inner col-xs-12 col-md-6">
            <div class="form-group">
                <?= Html::input(
                    'number',
                    'count',
                    null,
                    [
                        'id' => 'number-input',
                        'class' => 'b-count-input__input js-count-input__input form-control',
                        'placeholder' => 'Введите число',
                        'autofocus' => true,
                    ]
                ) ?>
            </div><!-- .input-group -->
            <div class="b-count-input__button-group">
                <?= Html::a('1', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 1,
                ]) ?>
                <?= Html::a('2', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 2,
                ]) ?>
                <?= Html::a('3', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 3,
                ]) ?>
                <?= Html::a('4', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 4,
                ]) ?>
                <?= Html::a('5', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 5,
                ]) ?>
                <?= Html::a('6', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 6,
                ]) ?>
                <?= Html::a('7', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 7,
                ]) ?>
                <?= Html::a('8', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 8,
                ]) ?>
                <?= Html::a('9', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 9,
                ]) ?>
                <?= Html::button(FA::icon('check'), [
                    'type' => 'submit',
                    'class' => 'b-count-input__button b-count-input__button_success',
                ]) ?>
                <?= Html::a('0', '#number-input', [
                    'class' => 'b-count-input__button js-count-input__button',
                    'data-value' => 0,
                ]) ?>
                <?= Html::a(FA::icon('chevron-left'), '#', [
                    'class' => 'b-count-input__button js-count-input__button_backspace',
                    'title' => 'Стереть'
                ]) ?>
            </div><!-- .b-count-input__button-group -->
        </div><!-- .b-count-input__inner -->
    </div><!-- .b-count-input -->
    <?= Html::endForm() ?>
</div>